# Generated by Django 5.2 on 2026-02-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=64)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('metric_name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('severity', models.IntegerField()),
                ('reason', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.host')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('disk', models.FloatField()),
                ('net_sent', models.FloatField()),
                ('net_recv', models.FloatField()),
                ('ping_ms', models.FloatField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.host')),
            ],
        ),
    ]
