# Generated by Django 6.0.2 on 2026-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_websitemonitor_websitecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsample',
            name='cpu_freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
