# Generated by Django 6.0.2 on 2026-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_host_user_alter_websitemonitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecheck',
            name='ssl_expiry_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='expected_keyword',
            field=models.CharField(blank=True, help_text='Keyword that must appear on the page', max_length=100, null=True),
        ),
    ]
