# Generated by Django 6.0.2 on 2026-03-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_websitecheck_ssl_expiry_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyevent',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
