# Generated by Django 6.0.2 on 2026-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_anomalyevent_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsample',
            name='disk_read_kb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='disk_write_kb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='top_processes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
